"""Migration template for generating new migration files.

This template is used to create new migration files with the proper structure.
"""

MIGRATION_TEMPLATE = '''"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision}
Create Date: ${create_date}

"""
from typing import Sequence, Union

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncConnection

# revision identifiers, used by the custom migration system
revision: str = "${up_revision}"
down_revision: Union[str, None] = ${down_revision_quoted}
branch_labels: Union[str, Sequence[str], None] = ${branch_labels_quoted}
depends_on: Union[str, Sequence[str], None] = ${depends_on_quoted}


async def upgrade(connection: AsyncConnection, context) -> None:
    """Upgrade database schema.
    
    Args:
        connection: Database connection
        context: Migration context with utilities
    """
    # ### commands auto generated by custom migration system ###
    pass
    # ### end custom migration system commands ###


async def downgrade(connection: AsyncConnection, context) -> None:
    """Downgrade database schema.
    
    Args:
        connection: Database connection
        context: Migration context with utilities
    """
    # ### commands auto generated by custom migration system ###
    pass
    # ### end custom migration system commands ###
'''

def get_template() -> str:
    """Get the migration template string.
    
    Returns:
        str: The migration template
    """
    return MIGRATION_TEMPLATE 